package com.zykj.carfigure.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zykj.carfigure.entity.AddressBean;

import com.zykj.carfigure.greendao.AddressBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressBeanDaoConfig;

    private final AddressBeanDao addressBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressBeanDaoConfig = daoConfigMap.get(AddressBeanDao.class).clone();
        addressBeanDaoConfig.initIdentityScope(type);

        addressBeanDao = new AddressBeanDao(addressBeanDaoConfig, this);

        registerDao(AddressBean.class, addressBeanDao);
    }
    
    public void clear() {
        addressBeanDaoConfig.clearIdentityScope();
    }

    public AddressBeanDao getAddressBeanDao() {
        return addressBeanDao;
    }

}
